id: PB5EA4848
initial_creation_type: input
source_metadata:
  title: Chatral Rinpoche
  language: fr
  description: 'Texts by and about the great Dzogchen master Chatral Sangye Dorje
    (bya bral sangs rgyas rdo rje, 1913–2015):'
  volume:
    aec6403b8e8248e1ba0991778238a997:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    90017e4f9696421fa0bce0643b14e4f4:
      title: The Benefits of Saving Lives
      parent: Advice
    e4ab3472f2c8440c8cf8c7e393c301bb:
      title: Words of Advice
      parent: Advice
    50e3de7ef0f1497d819952c1bd3dff63:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Aspiration Prayers
    89640cf42e904f41a24e7b445713de76:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Calling the Guru from Afar
    6cea5d0da9b54041b22f1f62826bca50:
      title: A Profound and Concise Guru Yoga
      parent: Guru Yoga
    760b9098e3934805981dda51690a5555:
      title: Introduction to The Excellent Path of Devotion
      parent: Introductions
    9d6adab7115f4e188a78382985b5f47f:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Long Life Prayers
    6255bf85da3a43b7b40adcfa1a77458f:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Long Life Prayers
    365b6b7f5e4740078a5d019405b6a74a:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Pilgrimage
    3acbf8ae534d4af897f1e936ff2cbabc:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Pilgrimage
    1f5197354d3b47ffa7557d88c2e84ba1:
      title: Essence of All the Buddhas of Past, Present and Future
      parent: Prayers
    d02d961acc1e4f609f4d598dd9bdf1b8:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Sādhanas
    4d9377e37fbc4b01b0f1985ef68bc52d:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-02-28T22:42:38.130950'
last_modified_at: '2022-02-28T22:42:38.130952'
